/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchAllRouteImport } from './routes/search-all'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MapRouteImport } from './routes/map'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LandsRouteImport } from './routes/lands'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FactoriesRouteImport } from './routes/factories'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as ControlCenterX7RouteImport } from './routes/control-center-x7'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as WholesaleIdRouteImport } from './routes/wholesale.$id'
import { Route as TendersIdRouteImport } from './routes/tenders.$id'
import { Route as RfqIdRouteImport } from './routes/rfq.$id'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as FactoriesIdRouteImport } from './routes/factories.$id'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedVerificationRouteImport } from './routes/_authenticated/verification'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedReferralProgramRouteImport } from './routes/_authenticated/referral-program'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPayoutsRouteImport } from './routes/_authenticated/payouts'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMarketingCenterRouteImport } from './routes/_authenticated/marketing-center'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompanyProfileExtraRouteImport } from './routes/_authenticated/company-profile-extra'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedCommissionsRouteImport } from './routes/_authenticated/commissions'
import { Route as AuthenticatedChooseRoleRouteImport } from './routes/_authenticated/choose-role'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiToolsRouteImport } from './routes/_authenticated/ai-tools'
import { Route as AuthenticatedAgentPerformanceRouteImport } from './routes/_authenticated/agent-performance'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin-withdrawals'
import { Route as AuthenticatedAdminRevenueRouteImport } from './routes/_authenticated/admin-revenue'
import { Route as AuthenticatedAdminPlatformSettingsRouteImport } from './routes/_authenticated/admin-platform-settings'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin-payments'
import { Route as AuthenticatedAdminOverviewRouteImport } from './routes/_authenticated/admin-overview'
import { Route as AuthenticatedAdminLaunchContentRouteImport } from './routes/_authenticated/admin-launch-content'
import { Route as AuthenticatedAdminExecutiveRouteImport } from './routes/_authenticated/admin-executive'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin-companies'
import { Route as AuthenticatedAdminCommissionsRouteImport } from './routes/_authenticated/admin-commissions'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedWholesaleNewRouteImport } from './routes/_authenticated/wholesale.new'
import { Route as AuthenticatedTendersNewRouteImport } from './routes/_authenticated/tenders.new'
import { Route as AuthenticatedTendersMineRouteImport } from './routes/_authenticated/tenders.mine'
import { Route as AuthenticatedRfqNewRouteImport } from './routes/_authenticated/rfq.new'
import { Route as AuthenticatedRfqMineRouteImport } from './routes/_authenticated/rfq.mine'
import { Route as AuthenticatedQuotationsNewRouteImport } from './routes/_authenticated/quotations.new'
import { Route as AuthenticatedQuotationsIdRouteImport } from './routes/_authenticated/quotations.$id'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedListingsNewRouteImport } from './routes/_authenticated/listings.new'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns.$id'
import { Route as AuthenticatedOrdersIdPayRouteImport } from './routes/_authenticated/orders.$id.pay'

const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchAllRoute = SearchAllRouteImport.update({
  id: '/search-all',
  path: '/search-all',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandsRoute = LandsRouteImport.update({
  id: '/lands',
  path: '/lands',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoriesRoute = FactoriesRouteImport.update({
  id: '/factories',
  path: '/factories',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlCenterX7Route = ControlCenterX7RouteImport.update({
  id: '/control-center-x7',
  path: '/control-center-x7',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleIdRoute = WholesaleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WholesaleRoute,
} as any)
const TendersIdRoute = TendersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TendersRoute,
} as any)
const RfqIdRoute = RfqIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RfqRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoriesIdRoute = FactoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FactoriesRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerificationRoute =
  AuthenticatedVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralProgramRoute =
  AuthenticatedReferralProgramRouteImport.update({
    id: '/referral-program',
    path: '/referral-program',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayoutsRoute = AuthenticatedPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingCenterRoute =
  AuthenticatedMarketingCenterRouteImport.update({
    id: '/marketing-center',
    path: '/marketing-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyProfileExtraRoute =
  AuthenticatedCompanyProfileExtraRouteImport.update({
    id: '/company-profile-extra',
    path: '/company-profile-extra',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommissionsRoute =
  AuthenticatedCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChooseRoleRoute = AuthenticatedChooseRoleRouteImport.update({
  id: '/choose-role',
  path: '/choose-role',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiToolsRoute = AuthenticatedAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentPerformanceRoute =
  AuthenticatedAgentPerformanceRouteImport.update({
    id: '/agent-performance',
    path: '/agent-performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/admin-withdrawals',
    path: '/admin-withdrawals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRevenueRoute =
  AuthenticatedAdminRevenueRouteImport.update({
    id: '/admin-revenue',
    path: '/admin-revenue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlatformSettingsRoute =
  AuthenticatedAdminPlatformSettingsRouteImport.update({
    id: '/admin-platform-settings',
    path: '/admin-platform-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin-payments',
    path: '/admin-payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOverviewRoute =
  AuthenticatedAdminOverviewRouteImport.update({
    id: '/admin-overview',
    path: '/admin-overview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLaunchContentRoute =
  AuthenticatedAdminLaunchContentRouteImport.update({
    id: '/admin-launch-content',
    path: '/admin-launch-content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminExecutiveRoute =
  AuthenticatedAdminExecutiveRouteImport.update({
    id: '/admin-executive',
    path: '/admin-executive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/admin-companies',
    path: '/admin-companies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCommissionsRoute =
  AuthenticatedAdminCommissionsRouteImport.update({
    id: '/admin-commissions',
    path: '/admin-commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWholesaleNewRoute =
  AuthenticatedWholesaleNewRouteImport.update({
    id: '/wholesale/new',
    path: '/wholesale/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTendersNewRoute = AuthenticatedTendersNewRouteImport.update({
  id: '/tenders/new',
  path: '/tenders/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTendersMineRoute =
  AuthenticatedTendersMineRouteImport.update({
    id: '/tenders/mine',
    path: '/tenders/mine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRfqNewRoute = AuthenticatedRfqNewRouteImport.update({
  id: '/rfq/new',
  path: '/rfq/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRfqMineRoute = AuthenticatedRfqMineRouteImport.update({
  id: '/rfq/mine',
  path: '/rfq/mine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsNewRoute =
  AuthenticatedQuotationsNewRouteImport.update({
    id: '/quotations/new',
    path: '/quotations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsIdRoute =
  AuthenticatedQuotationsIdRouteImport.update({
    id: '/quotations/$id',
    path: '/quotations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const AuthenticatedListingsNewRoute =
  AuthenticatedListingsNewRouteImport.update({
    id: '/listings/new',
    path: '/listings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCampaignsRoute,
  } as any)
const AuthenticatedOrdersIdPayRoute =
  AuthenticatedOrdersIdPayRouteImport.update({
    id: '/pay',
    path: '/pay',
    getParentRoute: () => AuthenticatedOrdersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/control-center-x7': typeof ControlCenterX7Route
  '/earn': typeof EarnRoute
  '/factories': typeof FactoriesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lands': typeof LandsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/real-estate': typeof RealEstateRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfq': typeof RfqRouteWithChildren
  '/search': typeof SearchRoute
  '/search-all': typeof SearchAllRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/tenders': typeof TendersRouteWithChildren
  '/terms': typeof TermsRoute
  '/wholesale': typeof WholesaleRouteWithChildren
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin-commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin-companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin-executive': typeof AuthenticatedAdminExecutiveRoute
  '/admin-launch-content': typeof AuthenticatedAdminLaunchContentRoute
  '/admin-overview': typeof AuthenticatedAdminOverviewRoute
  '/admin-payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin-platform-settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/admin-revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin-withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/agent-performance': typeof AuthenticatedAgentPerformanceRoute
  '/ai-tools': typeof AuthenticatedAiToolsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/campaigns': typeof AuthenticatedCampaignsRouteWithChildren
  '/choose-role': typeof AuthenticatedChooseRoleRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/company': typeof AuthenticatedCompanyRoute
  '/company-profile-extra': typeof AuthenticatedCompanyProfileExtraRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/marketing-center': typeof AuthenticatedMarketingCenterRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referral-program': typeof AuthenticatedReferralProgramRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/agents/$id': typeof AgentsIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/factories/$id': typeof FactoriesIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/r/$code': typeof RCodeRoute
  '/rfq/$id': typeof RfqIdRoute
  '/tenders/$id': typeof TendersIdRoute
  '/wholesale/$id': typeof WholesaleIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/listings/new': typeof AuthenticatedListingsNewRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRouteWithChildren
  '/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/rfq/mine': typeof AuthenticatedRfqMineRoute
  '/rfq/new': typeof AuthenticatedRfqNewRoute
  '/tenders/mine': typeof AuthenticatedTendersMineRoute
  '/tenders/new': typeof AuthenticatedTendersNewRoute
  '/wholesale/new': typeof AuthenticatedWholesaleNewRoute
  '/orders/$id/pay': typeof AuthenticatedOrdersIdPayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/control-center-x7': typeof ControlCenterX7Route
  '/earn': typeof EarnRoute
  '/factories': typeof FactoriesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lands': typeof LandsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/real-estate': typeof RealEstateRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfq': typeof RfqRouteWithChildren
  '/search': typeof SearchRoute
  '/search-all': typeof SearchAllRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/tenders': typeof TendersRouteWithChildren
  '/terms': typeof TermsRoute
  '/wholesale': typeof WholesaleRouteWithChildren
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin-commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin-companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin-executive': typeof AuthenticatedAdminExecutiveRoute
  '/admin-launch-content': typeof AuthenticatedAdminLaunchContentRoute
  '/admin-overview': typeof AuthenticatedAdminOverviewRoute
  '/admin-payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin-platform-settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/admin-revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin-withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/agent-performance': typeof AuthenticatedAgentPerformanceRoute
  '/ai-tools': typeof AuthenticatedAiToolsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/campaigns': typeof AuthenticatedCampaignsRouteWithChildren
  '/choose-role': typeof AuthenticatedChooseRoleRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/company': typeof AuthenticatedCompanyRoute
  '/company-profile-extra': typeof AuthenticatedCompanyProfileExtraRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/marketing-center': typeof AuthenticatedMarketingCenterRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referral-program': typeof AuthenticatedReferralProgramRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/agents/$id': typeof AgentsIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/factories/$id': typeof FactoriesIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/r/$code': typeof RCodeRoute
  '/rfq/$id': typeof RfqIdRoute
  '/tenders/$id': typeof TendersIdRoute
  '/wholesale/$id': typeof WholesaleIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/listings/new': typeof AuthenticatedListingsNewRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRouteWithChildren
  '/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/rfq/mine': typeof AuthenticatedRfqMineRoute
  '/rfq/new': typeof AuthenticatedRfqNewRoute
  '/tenders/mine': typeof AuthenticatedTendersMineRoute
  '/tenders/new': typeof AuthenticatedTendersNewRoute
  '/wholesale/new': typeof AuthenticatedWholesaleNewRoute
  '/orders/$id/pay': typeof AuthenticatedOrdersIdPayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/control-center-x7': typeof ControlCenterX7Route
  '/earn': typeof EarnRoute
  '/factories': typeof FactoriesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lands': typeof LandsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/real-estate': typeof RealEstateRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rfq': typeof RfqRouteWithChildren
  '/search': typeof SearchRoute
  '/search-all': typeof SearchAllRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscribe': typeof SubscribeRoute
  '/tenders': typeof TendersRouteWithChildren
  '/terms': typeof TermsRoute
  '/wholesale': typeof WholesaleRouteWithChildren
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/admin-commissions': typeof AuthenticatedAdminCommissionsRoute
  '/_authenticated/admin-companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin-executive': typeof AuthenticatedAdminExecutiveRoute
  '/_authenticated/admin-launch-content': typeof AuthenticatedAdminLaunchContentRoute
  '/_authenticated/admin-overview': typeof AuthenticatedAdminOverviewRoute
  '/_authenticated/admin-payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin-platform-settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/_authenticated/admin-revenue': typeof AuthenticatedAdminRevenueRoute
  '/_authenticated/admin-withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/agent-performance': typeof AuthenticatedAgentPerformanceRoute
  '/_authenticated/ai-tools': typeof AuthenticatedAiToolsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRouteWithChildren
  '/_authenticated/choose-role': typeof AuthenticatedChooseRoleRoute
  '/_authenticated/commissions': typeof AuthenticatedCommissionsRoute
  '/_authenticated/company': typeof AuthenticatedCompanyRoute
  '/_authenticated/company-profile-extra': typeof AuthenticatedCompanyProfileExtraRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/marketing-center': typeof AuthenticatedMarketingCenterRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/payouts': typeof AuthenticatedPayoutsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referral-program': typeof AuthenticatedReferralProgramRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/verification': typeof AuthenticatedVerificationRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/agents/$id': typeof AgentsIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/factories/$id': typeof FactoriesIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/r/$code': typeof RCodeRoute
  '/rfq/$id': typeof RfqIdRoute
  '/tenders/$id': typeof TendersIdRoute
  '/wholesale/$id': typeof WholesaleIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/listings/new': typeof AuthenticatedListingsNewRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRouteWithChildren
  '/_authenticated/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/_authenticated/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/_authenticated/rfq/mine': typeof AuthenticatedRfqMineRoute
  '/_authenticated/rfq/new': typeof AuthenticatedRfqNewRoute
  '/_authenticated/tenders/mine': typeof AuthenticatedTendersMineRoute
  '/_authenticated/tenders/new': typeof AuthenticatedTendersNewRoute
  '/_authenticated/wholesale/new': typeof AuthenticatedWholesaleNewRoute
  '/_authenticated/orders/$id/pay': typeof AuthenticatedOrdersIdPayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/control-center-x7'
    | '/earn'
    | '/factories'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/lands'
    | '/leaderboard'
    | '/map'
    | '/marketplace'
    | '/pricing'
    | '/privacy'
    | '/real-estate'
    | '/refund-policy'
    | '/reset-password'
    | '/rfq'
    | '/search'
    | '/search-all'
    | '/sitemap.xml'
    | '/subscribe'
    | '/tenders'
    | '/terms'
    | '/wholesale'
    | '/achievements'
    | '/admin-commissions'
    | '/admin-companies'
    | '/admin-executive'
    | '/admin-launch-content'
    | '/admin-overview'
    | '/admin-payments'
    | '/admin-platform-settings'
    | '/admin-revenue'
    | '/admin-withdrawals'
    | '/agent'
    | '/agent-performance'
    | '/ai-tools'
    | '/analytics'
    | '/campaigns'
    | '/choose-role'
    | '/commissions'
    | '/company'
    | '/company-profile-extra'
    | '/dashboard'
    | '/favorites'
    | '/invoices'
    | '/leads'
    | '/marketing-center'
    | '/messages'
    | '/moderation'
    | '/orders'
    | '/payouts'
    | '/profile'
    | '/referral-program'
    | '/referrals'
    | '/verification'
    | '/wallet'
    | '/agents/$id'
    | '/auth/callback'
    | '/categories/$slug'
    | '/companies/$id'
    | '/factories/$id'
    | '/listings/$id'
    | '/r/$code'
    | '/rfq/$id'
    | '/tenders/$id'
    | '/wholesale/$id'
    | '/companies/'
    | '/campaigns/$id'
    | '/listings/new'
    | '/orders/$id'
    | '/quotations/$id'
    | '/quotations/new'
    | '/rfq/mine'
    | '/rfq/new'
    | '/tenders/mine'
    | '/tenders/new'
    | '/wholesale/new'
    | '/orders/$id/pay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/control-center-x7'
    | '/earn'
    | '/factories'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/lands'
    | '/leaderboard'
    | '/map'
    | '/marketplace'
    | '/pricing'
    | '/privacy'
    | '/real-estate'
    | '/refund-policy'
    | '/reset-password'
    | '/rfq'
    | '/search'
    | '/search-all'
    | '/sitemap.xml'
    | '/subscribe'
    | '/tenders'
    | '/terms'
    | '/wholesale'
    | '/achievements'
    | '/admin-commissions'
    | '/admin-companies'
    | '/admin-executive'
    | '/admin-launch-content'
    | '/admin-overview'
    | '/admin-payments'
    | '/admin-platform-settings'
    | '/admin-revenue'
    | '/admin-withdrawals'
    | '/agent'
    | '/agent-performance'
    | '/ai-tools'
    | '/analytics'
    | '/campaigns'
    | '/choose-role'
    | '/commissions'
    | '/company'
    | '/company-profile-extra'
    | '/dashboard'
    | '/favorites'
    | '/invoices'
    | '/leads'
    | '/marketing-center'
    | '/messages'
    | '/moderation'
    | '/orders'
    | '/payouts'
    | '/profile'
    | '/referral-program'
    | '/referrals'
    | '/verification'
    | '/wallet'
    | '/agents/$id'
    | '/auth/callback'
    | '/categories/$slug'
    | '/companies/$id'
    | '/factories/$id'
    | '/listings/$id'
    | '/r/$code'
    | '/rfq/$id'
    | '/tenders/$id'
    | '/wholesale/$id'
    | '/companies'
    | '/campaigns/$id'
    | '/listings/new'
    | '/orders/$id'
    | '/quotations/$id'
    | '/quotations/new'
    | '/rfq/mine'
    | '/rfq/new'
    | '/tenders/mine'
    | '/tenders/new'
    | '/wholesale/new'
    | '/orders/$id/pay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/agents'
    | '/auth'
    | '/categories'
    | '/contact'
    | '/control-center-x7'
    | '/earn'
    | '/factories'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/lands'
    | '/leaderboard'
    | '/map'
    | '/marketplace'
    | '/pricing'
    | '/privacy'
    | '/real-estate'
    | '/refund-policy'
    | '/reset-password'
    | '/rfq'
    | '/search'
    | '/search-all'
    | '/sitemap.xml'
    | '/subscribe'
    | '/tenders'
    | '/terms'
    | '/wholesale'
    | '/_authenticated/achievements'
    | '/_authenticated/admin-commissions'
    | '/_authenticated/admin-companies'
    | '/_authenticated/admin-executive'
    | '/_authenticated/admin-launch-content'
    | '/_authenticated/admin-overview'
    | '/_authenticated/admin-payments'
    | '/_authenticated/admin-platform-settings'
    | '/_authenticated/admin-revenue'
    | '/_authenticated/admin-withdrawals'
    | '/_authenticated/agent'
    | '/_authenticated/agent-performance'
    | '/_authenticated/ai-tools'
    | '/_authenticated/analytics'
    | '/_authenticated/campaigns'
    | '/_authenticated/choose-role'
    | '/_authenticated/commissions'
    | '/_authenticated/company'
    | '/_authenticated/company-profile-extra'
    | '/_authenticated/dashboard'
    | '/_authenticated/favorites'
    | '/_authenticated/invoices'
    | '/_authenticated/leads'
    | '/_authenticated/marketing-center'
    | '/_authenticated/messages'
    | '/_authenticated/moderation'
    | '/_authenticated/orders'
    | '/_authenticated/payouts'
    | '/_authenticated/profile'
    | '/_authenticated/referral-program'
    | '/_authenticated/referrals'
    | '/_authenticated/verification'
    | '/_authenticated/wallet'
    | '/agents/$id'
    | '/auth/callback'
    | '/categories/$slug'
    | '/companies/$id'
    | '/factories/$id'
    | '/listings/$id'
    | '/r/$code'
    | '/rfq/$id'
    | '/tenders/$id'
    | '/wholesale/$id'
    | '/companies/'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/listings/new'
    | '/_authenticated/orders/$id'
    | '/_authenticated/quotations/$id'
    | '/_authenticated/quotations/new'
    | '/_authenticated/rfq/mine'
    | '/_authenticated/rfq/new'
    | '/_authenticated/tenders/mine'
    | '/_authenticated/tenders/new'
    | '/_authenticated/wholesale/new'
    | '/_authenticated/orders/$id/pay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ContactRoute: typeof ContactRoute
  ControlCenterX7Route: typeof ControlCenterX7Route
  EarnRoute: typeof EarnRoute
  FactoriesRoute: typeof FactoriesRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LandsRoute: typeof LandsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MapRoute: typeof MapRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RealEstateRoute: typeof RealEstateRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RfqRoute: typeof RfqRouteWithChildren
  SearchRoute: typeof SearchRoute
  SearchAllRoute: typeof SearchAllRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscribeRoute: typeof SubscribeRoute
  TendersRoute: typeof TendersRouteWithChildren
  TermsRoute: typeof TermsRoute
  WholesaleRoute: typeof WholesaleRouteWithChildren
  CompaniesIdRoute: typeof CompaniesIdRoute
  ListingsIdRoute: typeof ListingsIdRoute
  RCodeRoute: typeof RCodeRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-all': {
      id: '/search-all'
      path: '/search-all'
      fullPath: '/search-all'
      preLoaderRoute: typeof SearchAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lands': {
      id: '/lands'
      path: '/lands'
      fullPath: '/lands'
      preLoaderRoute: typeof LandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factories': {
      id: '/factories'
      path: '/factories'
      fullPath: '/factories'
      preLoaderRoute: typeof FactoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-center-x7': {
      id: '/control-center-x7'
      path: '/control-center-x7'
      fullPath: '/control-center-x7'
      preLoaderRoute: typeof ControlCenterX7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/$id': {
      id: '/wholesale/$id'
      path: '/$id'
      fullPath: '/wholesale/$id'
      preLoaderRoute: typeof WholesaleIdRouteImport
      parentRoute: typeof WholesaleRoute
    }
    '/tenders/$id': {
      id: '/tenders/$id'
      path: '/$id'
      fullPath: '/tenders/$id'
      preLoaderRoute: typeof TendersIdRouteImport
      parentRoute: typeof TendersRoute
    }
    '/rfq/$id': {
      id: '/rfq/$id'
      path: '/$id'
      fullPath: '/rfq/$id'
      preLoaderRoute: typeof RfqIdRouteImport
      parentRoute: typeof RfqRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factories/$id': {
      id: '/factories/$id'
      path: '/$id'
      fullPath: '/factories/$id'
      preLoaderRoute: typeof FactoriesIdRouteImport
      parentRoute: typeof FactoriesRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verification': {
      id: '/_authenticated/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AuthenticatedVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral-program': {
      id: '/_authenticated/referral-program'
      path: '/referral-program'
      fullPath: '/referral-program'
      preLoaderRoute: typeof AuthenticatedReferralProgramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts': {
      id: '/_authenticated/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AuthenticatedPayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing-center': {
      id: '/_authenticated/marketing-center'
      path: '/marketing-center'
      fullPath: '/marketing-center'
      preLoaderRoute: typeof AuthenticatedMarketingCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-profile-extra': {
      id: '/_authenticated/company-profile-extra'
      path: '/company-profile-extra'
      fullPath: '/company-profile-extra'
      preLoaderRoute: typeof AuthenticatedCompanyProfileExtraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commissions': {
      id: '/_authenticated/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AuthenticatedCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/choose-role': {
      id: '/_authenticated/choose-role'
      path: '/choose-role'
      fullPath: '/choose-role'
      preLoaderRoute: typeof AuthenticatedChooseRoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-tools': {
      id: '/_authenticated/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AuthenticatedAiToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent-performance': {
      id: '/_authenticated/agent-performance'
      path: '/agent-performance'
      fullPath: '/agent-performance'
      preLoaderRoute: typeof AuthenticatedAgentPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-withdrawals': {
      id: '/_authenticated/admin-withdrawals'
      path: '/admin-withdrawals'
      fullPath: '/admin-withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-revenue': {
      id: '/_authenticated/admin-revenue'
      path: '/admin-revenue'
      fullPath: '/admin-revenue'
      preLoaderRoute: typeof AuthenticatedAdminRevenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-platform-settings': {
      id: '/_authenticated/admin-platform-settings'
      path: '/admin-platform-settings'
      fullPath: '/admin-platform-settings'
      preLoaderRoute: typeof AuthenticatedAdminPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-payments': {
      id: '/_authenticated/admin-payments'
      path: '/admin-payments'
      fullPath: '/admin-payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-overview': {
      id: '/_authenticated/admin-overview'
      path: '/admin-overview'
      fullPath: '/admin-overview'
      preLoaderRoute: typeof AuthenticatedAdminOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-launch-content': {
      id: '/_authenticated/admin-launch-content'
      path: '/admin-launch-content'
      fullPath: '/admin-launch-content'
      preLoaderRoute: typeof AuthenticatedAdminLaunchContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-executive': {
      id: '/_authenticated/admin-executive'
      path: '/admin-executive'
      fullPath: '/admin-executive'
      preLoaderRoute: typeof AuthenticatedAdminExecutiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-companies': {
      id: '/_authenticated/admin-companies'
      path: '/admin-companies'
      fullPath: '/admin-companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-commissions': {
      id: '/_authenticated/admin-commissions'
      path: '/admin-commissions'
      fullPath: '/admin-commissions'
      preLoaderRoute: typeof AuthenticatedAdminCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wholesale/new': {
      id: '/_authenticated/wholesale/new'
      path: '/wholesale/new'
      fullPath: '/wholesale/new'
      preLoaderRoute: typeof AuthenticatedWholesaleNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenders/new': {
      id: '/_authenticated/tenders/new'
      path: '/tenders/new'
      fullPath: '/tenders/new'
      preLoaderRoute: typeof AuthenticatedTendersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenders/mine': {
      id: '/_authenticated/tenders/mine'
      path: '/tenders/mine'
      fullPath: '/tenders/mine'
      preLoaderRoute: typeof AuthenticatedTendersMineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfq/new': {
      id: '/_authenticated/rfq/new'
      path: '/rfq/new'
      fullPath: '/rfq/new'
      preLoaderRoute: typeof AuthenticatedRfqNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rfq/mine': {
      id: '/_authenticated/rfq/mine'
      path: '/rfq/mine'
      fullPath: '/rfq/mine'
      preLoaderRoute: typeof AuthenticatedRfqMineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/new': {
      id: '/_authenticated/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof AuthenticatedQuotationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/$id': {
      id: '/_authenticated/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof AuthenticatedQuotationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/_authenticated/listings/new': {
      id: '/_authenticated/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof AuthenticatedListingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedCampaignsRoute
    }
    '/_authenticated/orders/$id/pay': {
      id: '/_authenticated/orders/$id/pay'
      path: '/pay'
      fullPath: '/orders/$id/pay'
      preLoaderRoute: typeof AuthenticatedOrdersIdPayRouteImport
      parentRoute: typeof AuthenticatedOrdersIdRoute
    }
  }
}

interface AuthenticatedCampaignsRouteChildren {
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
}

const AuthenticatedCampaignsRouteChildren: AuthenticatedCampaignsRouteChildren =
  {
    AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
  }

const AuthenticatedCampaignsRouteWithChildren =
  AuthenticatedCampaignsRoute._addFileChildren(
    AuthenticatedCampaignsRouteChildren,
  )

interface AuthenticatedOrdersIdRouteChildren {
  AuthenticatedOrdersIdPayRoute: typeof AuthenticatedOrdersIdPayRoute
}

const AuthenticatedOrdersIdRouteChildren: AuthenticatedOrdersIdRouteChildren = {
  AuthenticatedOrdersIdPayRoute: AuthenticatedOrdersIdPayRoute,
}

const AuthenticatedOrdersIdRouteWithChildren =
  AuthenticatedOrdersIdRoute._addFileChildren(
    AuthenticatedOrdersIdRouteChildren,
  )

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRouteWithChildren
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRouteWithChildren,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAdminCommissionsRoute: typeof AuthenticatedAdminCommissionsRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminExecutiveRoute: typeof AuthenticatedAdminExecutiveRoute
  AuthenticatedAdminLaunchContentRoute: typeof AuthenticatedAdminLaunchContentRoute
  AuthenticatedAdminOverviewRoute: typeof AuthenticatedAdminOverviewRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPlatformSettingsRoute: typeof AuthenticatedAdminPlatformSettingsRoute
  AuthenticatedAdminRevenueRoute: typeof AuthenticatedAdminRevenueRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedAgentPerformanceRoute: typeof AuthenticatedAgentPerformanceRoute
  AuthenticatedAiToolsRoute: typeof AuthenticatedAiToolsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRouteWithChildren
  AuthenticatedChooseRoleRoute: typeof AuthenticatedChooseRoleRoute
  AuthenticatedCommissionsRoute: typeof AuthenticatedCommissionsRoute
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRoute
  AuthenticatedCompanyProfileExtraRoute: typeof AuthenticatedCompanyProfileExtraRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMarketingCenterRoute: typeof AuthenticatedMarketingCenterRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedPayoutsRoute: typeof AuthenticatedPayoutsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralProgramRoute: typeof AuthenticatedReferralProgramRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedVerificationRoute: typeof AuthenticatedVerificationRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedListingsNewRoute: typeof AuthenticatedListingsNewRoute
  AuthenticatedQuotationsIdRoute: typeof AuthenticatedQuotationsIdRoute
  AuthenticatedQuotationsNewRoute: typeof AuthenticatedQuotationsNewRoute
  AuthenticatedRfqMineRoute: typeof AuthenticatedRfqMineRoute
  AuthenticatedRfqNewRoute: typeof AuthenticatedRfqNewRoute
  AuthenticatedTendersMineRoute: typeof AuthenticatedTendersMineRoute
  AuthenticatedTendersNewRoute: typeof AuthenticatedTendersNewRoute
  AuthenticatedWholesaleNewRoute: typeof AuthenticatedWholesaleNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAdminCommissionsRoute: AuthenticatedAdminCommissionsRoute,
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminExecutiveRoute: AuthenticatedAdminExecutiveRoute,
  AuthenticatedAdminLaunchContentRoute: AuthenticatedAdminLaunchContentRoute,
  AuthenticatedAdminOverviewRoute: AuthenticatedAdminOverviewRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPlatformSettingsRoute:
    AuthenticatedAdminPlatformSettingsRoute,
  AuthenticatedAdminRevenueRoute: AuthenticatedAdminRevenueRoute,
  AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedAgentPerformanceRoute: AuthenticatedAgentPerformanceRoute,
  AuthenticatedAiToolsRoute: AuthenticatedAiToolsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRouteWithChildren,
  AuthenticatedChooseRoleRoute: AuthenticatedChooseRoleRoute,
  AuthenticatedCommissionsRoute: AuthenticatedCommissionsRoute,
  AuthenticatedCompanyRoute: AuthenticatedCompanyRoute,
  AuthenticatedCompanyProfileExtraRoute: AuthenticatedCompanyProfileExtraRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMarketingCenterRoute: AuthenticatedMarketingCenterRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedPayoutsRoute: AuthenticatedPayoutsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralProgramRoute: AuthenticatedReferralProgramRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedVerificationRoute: AuthenticatedVerificationRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedListingsNewRoute: AuthenticatedListingsNewRoute,
  AuthenticatedQuotationsIdRoute: AuthenticatedQuotationsIdRoute,
  AuthenticatedQuotationsNewRoute: AuthenticatedQuotationsNewRoute,
  AuthenticatedRfqMineRoute: AuthenticatedRfqMineRoute,
  AuthenticatedRfqNewRoute: AuthenticatedRfqNewRoute,
  AuthenticatedTendersMineRoute: AuthenticatedTendersMineRoute,
  AuthenticatedTendersNewRoute: AuthenticatedTendersNewRoute,
  AuthenticatedWholesaleNewRoute: AuthenticatedWholesaleNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface FactoriesRouteChildren {
  FactoriesIdRoute: typeof FactoriesIdRoute
}

const FactoriesRouteChildren: FactoriesRouteChildren = {
  FactoriesIdRoute: FactoriesIdRoute,
}

const FactoriesRouteWithChildren = FactoriesRoute._addFileChildren(
  FactoriesRouteChildren,
)

interface RfqRouteChildren {
  RfqIdRoute: typeof RfqIdRoute
}

const RfqRouteChildren: RfqRouteChildren = {
  RfqIdRoute: RfqIdRoute,
}

const RfqRouteWithChildren = RfqRoute._addFileChildren(RfqRouteChildren)

interface TendersRouteChildren {
  TendersIdRoute: typeof TendersIdRoute
}

const TendersRouteChildren: TendersRouteChildren = {
  TendersIdRoute: TendersIdRoute,
}

const TendersRouteWithChildren =
  TendersRoute._addFileChildren(TendersRouteChildren)

interface WholesaleRouteChildren {
  WholesaleIdRoute: typeof WholesaleIdRoute
}

const WholesaleRouteChildren: WholesaleRouteChildren = {
  WholesaleIdRoute: WholesaleIdRoute,
}

const WholesaleRouteWithChildren = WholesaleRoute._addFileChildren(
  WholesaleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  ContactRoute: ContactRoute,
  ControlCenterX7Route: ControlCenterX7Route,
  EarnRoute: EarnRoute,
  FactoriesRoute: FactoriesRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LandsRoute: LandsRoute,
  LeaderboardRoute: LeaderboardRoute,
  MapRoute: MapRoute,
  MarketplaceRoute: MarketplaceRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RealEstateRoute: RealEstateRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RfqRoute: RfqRouteWithChildren,
  SearchRoute: SearchRoute,
  SearchAllRoute: SearchAllRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscribeRoute: SubscribeRoute,
  TendersRoute: TendersRouteWithChildren,
  TermsRoute: TermsRoute,
  WholesaleRoute: WholesaleRouteWithChildren,
  CompaniesIdRoute: CompaniesIdRoute,
  ListingsIdRoute: ListingsIdRoute,
  RCodeRoute: RCodeRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
