GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO anon, authenticated;
GRANT SELECT ON public.listings TO anon, authenticated;
GRANT SELECT ON public.companies TO anon, authenticated;
GRANT SELECT ON public.agents TO anon, authenticated;
GRANT SELECT ON public.factories TO anon, authenticated;
GRANT SELECT ON public.rfqs TO anon, authenticated;
GRANT SELECT ON public.tenders TO anon, authenticated;
GRANT SELECT ON public.wholesale_listings TO anon, authenticated;
GRANT SELECT ON public.profiles TO anon, authenticated;
GRANT SELECT ON public.business_categories TO anon, authenticated;
GRANT SELECT ON public.agent_landing_pages TO anon, authenticated;
GRANT SELECT ON public.company_profiles_extra TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.favorites TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.leads TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rfq_offers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tender_proposals TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.wholesale_orders TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.referrals TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.company_referrals TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.agent_applications TO authenticated;
GRANT SELECT, UPDATE ON public.wallets TO authenticated;
GRANT SELECT ON public.wallet_transactions TO authenticated;
GRANT SELECT ON public.commissions TO authenticated;
GRANT SELECT ON public.invoices TO authenticated;
GRANT SELECT ON public.payments TO authenticated;
GRANT SELECT ON public.subscriptions TO authenticated;
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;