// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `إعدادات Supabase المطلوبة غير مكتملة على الخادم: ${missing.join(", ")}.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("تعذر التحقق من بيانات الطلب.");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("يجب تسجيل الدخول لإكمال هذه العملية.");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("صيغة جلسة الدخول غير صالحة.");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("جلسة الدخول غير متاحة.");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("انتهت جلسة الدخول أو أصبحت غير صالحة.");
    }

    if (!data.claims.sub) {
      throw new Error("تعذر تحديد الحساب من جلسة الدخول.");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
